spring:
# 配置整个单体应用在eureka服务上的名称.
  application:
    name: order-service
# 配置整个连接数据库连接信息.
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: root
# 设置spring.data.jpa.show-sql为true,将生成的hql语句打印到控制台上.
  jpa:
    show-sql: true
# 配置ribbon的负载均衡策略(random随机访问,默认为roundrobin轮询发送).
# product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  dev
server:
  port: 8085

# 去除掉hystrix之前的application前缀(在spring cloud RELEASE正式版中不生效).
#management:
#  server:
#    servlet:
#      context-path: /

# 将order订单服务注册到eureka服务上(整个order项目的配置文件已存放于github).
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

# 配置整个连接数据库连接信息.
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
#    username: dong
#    password: java
# 设置spring.data.jpa.show-sql为true,将生成的hql语句打印到控制台上.
#  jpa:
#    show-sql: true

# 配置ribbon的负载均衡策略(random随机访问,默认为roundrobin轮询发送).
# product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

## 在整个配置中/{label}-/{name}-{profiles}
## 其中label在git中代表的是分支名 branch, name代表的是文件名 filename(servername), profiles表示的是环境名称
