spring:
  # 配置数据库驱动连接信息.
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: microservice
# 将Jpa生成的sql打印到控制台上.
  jpa:
    show-sql: true
server:
  port: 8083
