# 配置整个商品应用的名称
spring:
  application:
    name: product-service
  # 配置数据库驱动连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  # 将Jpa生成的sql打印到控制台上
  jpa:
    show-sql: true
  # 开启spring cloud的config服务发现的配置
  cloud:
    stream:
      default-binder: kafka
      # 通过spring cloud stream.binding.input属性将input通道映射到decreaseStockTopic队列
      bindings:
        input:
          destination: decreaseStockTopic
          content-type: application/json
          group: product-consumer-group
      kafka:
        # stream.bindings.kafka属性告诉spring,将使用kafka作为服务中的消息总线
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181

# 调整feign中的logging日志的级别为debug
logging:
  level:
    org.springframework.cloud.openfeign: debug

server:
  port: 8083
