spring:
  # 配置数据库驱动连接信息.
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/springcloud_sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
# 将Jpa生成的sql打印到控制台上.
  jpa:
    show-sql: true
  redis:
    host: 192.168.0.103
    port: 6379
server:
  port: 8084
  
